import '../../styles/globals.css'
//import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'

import Link from "next/link";
import { Providers } from "./providers";
import styles from './page.module.css';
//import { ChakraProvider } from "@chakra-ui/react";
//const inter = Inter({ subsets: ['latin'] })
const links = [
  {
    label: "Home",
    route: "/",
  },
  {
    label: "About",
    route: "/about",
  },
  {
    label: "Login",
    route: "/login",
  },
];
/*
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <head>
          <title>App con Next 13</title>
        </head>
        <body>
          <header>
            <nav className={styles.navContainer}>

                {links.map(({ label, route }) => (
                 
                    <Link key={label} href={route} className={styles.item}>{label}</Link>
                ))}
            </nav>
          </header>
          <Providers>
          {children}
          </Providers>
        </body>
      </html>
  );
}
