import '../../styles/globals.css'
//import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'

import Link from "next/link";
import { Providers } from "./providers";
//import { ChakraProvider } from "@chakra-ui/react";
//const inter = Inter({ subsets: ['latin'] })
const links = [
  {
    label: "Home",
    route: "/",
  },
  {
    label: "About",
    route: "/about",
  },
  {
    label: "Login",
    route: "/login",
  },
];
/*
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <head>
          <title>App con Next 13</title>
        </head>
        <body>
          <header>
            <nav>
              <ul>
                {links.map(({ label, route }) => (
                  <li key={route}>
                    <Link href={route}>{label}</Link>
                  </li>
                ))}
              </ul>
            </nav>
          </header>
          <Providers>
          {children}
          </Providers>
        </body>
      </html>
  );
}
